Module2 task1
htmlacademy-react/2106301-six-cities-10 pull request #3
Opened 2022-07-08 15:57 UTC by Capsonchik

1. Add mainPage
2. Add favouritesPage
3. Add loginPage
4. Add some props

2022-07-09 10:04 UTC, Seothp requested changes

2022-07-09 10:04 UTC, Seothp commented on project/src/pages/mainPage/main.tsx
> +import Card from '../../components/card/card';
**codestyle** пустая строка между импортами и кодом
```
import Card from '../../components/card/card';

type Props = {
  places: number;
};
```

2022-07-09 10:22 UTC, Seothp requested changes

2022-07-09 10:22 UTC, Seothp commented on project/src/pages/favorites/favorites.tsx
> +function Favorites() {
Почему тут просто Favorites, а в main - MainPage? давай приведем их к одному виду и либо везде добавим Page, либо везде уберем.
Еще давай переименуем файлы что бы они совпадали с именем экспортируемого файла(main => main-page)(если мы будем оставлять с Page)

2022-07-10 07:44 UTC, Capsonchik commented on project/src/components/app/app.tsx
> +  places: number;
Пофиксил.

2022-07-10 07:45 UTC, Capsonchik commented on project/src/components/app/app.tsx
> +    <MainPage places = {places}/>
Пофиксил.

2022-07-10 07:49 UTC, Capsonchik commented on project/src/index.tsx
> +const places = 100;
Пофиксил

2022-07-10 07:49 UTC, Capsonchik commented on project/src/index.tsx
> +    <App places ={places}/>
Пофиксил

2022-07-10 07:53 UTC, Capsonchik commented on project/src/pages/mainPage/main.tsx
> +import Card from '../../components/card/card';
Вроде пофиксил

2022-07-10 08:00 UTC, Capsonchik commented on project/src/pages/favorites/favorites.tsx
> +function Favorites() {
Пофиксил

2022-07-10 08:56 UTC, Seothp commented on project/src/components/app/app.tsx
> +type countOfAvailablePlaces = {
Я иммел ввиду не тип, а переменную places и имя пропса в остальных компонентах :)

2022-07-10 08:56 UTC, Seothp commented on project/src/pages/mainPage/main-page.tsx
> +type countOfAvailablePlaces = {
тоже самое что и в app.tsx

2022-07-10 08:56 UTC, Seothp commented on project/src/components/app/app.tsx
> +    <MainPage places = {places}/>
Но они все еще есть(

2022-07-10 09:02 UTC, Capsonchik commented on project/src/components/app/app.tsx
> +    <MainPage places = {places}/>
Пофиксил снова( Как же это нечитабельно((

2022-07-10 09:05 UTC, Capsonchik commented on project/src/components/app/app.tsx
> +type countOfAvailablePlaces = {
Принял, пофиксил, понял, осознал =) В след раз буду умнее =)

2022-07-10 09:09 UTC, merged